version: "2"
services:
  node:
    container_name: rest
    image: "rest:latest"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    networks:
      - lsio
    command: "npm start"

  node1:
    container_name: angular
    image: "angular:latest"
    networks:
      - lsio
networks:
  lsio:
    external: true