version: "2"
services:
  node:
    container_name: rest
    image: "rest:latest"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - /home/node/app
    networks:
      - lsio
    command: "npm start"

networks:
  lsio:
    external: true